<a href="https://colab.research.google.com/github/2147118Joshua/Machine_Learning/blob/main/ml%20KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np 
import csv
import matplotlib.pyplot as plt 
import seaborn as sns   #Python data visualization library based on matplotlib
from sklearn.linear_model import LinearRegression
from numpy.linalg import inv,lstsq
from numpy import dot, transpose
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import files
uploaded=files.upload()

Saving insurance copy.csv to insurance copy.csv


In [3]:
df=pd.read_csv('insurance copy.csv')

In [ ]:
youdata = youtube_data.copy()

In [4]:
df.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

Identifying unique values

In [6]:
df.age.unique()

array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
       59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
       20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39])

Finding Missing values

In [7]:
df.isnull()

age    bmi  children  charges
0     False  False     False    False
1     False  False     False    False
2     False  False     False    False
3     False  False     False    False
4     False  False     False    False
...     ...    ...       ...      ...
1333  False  False     False    False
1334  False  False     False    False
1335  False  False     False    False
1336  False  False     False    False
1337  False  False     False    False

[1338 rows x 4 columns]

Replacing missing values and null values

In [8]:
df=df.fillna(0)

In [9]:
df.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [10]:
X=df.iloc[:,0].values
Y=df.iloc[:,1:].values

Spliting dataset into test (20%) and train(80%)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

Normalizing the data using standard scaler

In [12]:
scaler = StandardScaler()
scaler.fit(y_train)

y_train = scaler.transform(y_train)
y_test = scaler.transform(y_test)



KNN model fitting considering K=5 and metric = euclidean

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)

Confusion matrix, accuracy measures, classification report

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[5 6 1 ... 1 0 0]
 [2 6 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]
              precision    recall  f1-score   support

          18       0.19      0.28      0.22        18
          19       0.18      0.55      0.27        11
          20       0.11      0.11      0.11         9
          21       0.20      0.17      0.18         6
          22       0.00      0.00      0.00         5
          23       0.00      0.00      0.00         7
          24       0.00      0.00      0.00         7
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         3
          27       0.00      0.00      0.00        10
          28       0.00      0.00      0.00         4
          29       0.00      0.00      0.00        11
          30       0.09      0.20      0.13         5
          31       0.00      0.00      0.00         8
          32       0.00      0.00      0.00         3
          33   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


KNN model fitting considering K=3 and metric = manhattan

In [17]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3,metric='manhattan')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)


Confusion matrix, accuracy measures, classification report

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[5 6 0 ... 0 0 0]
 [3 6 0 ... 0 0 0]
 [2 3 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
              precision    recall  f1-score   support

          18       0.19      0.28      0.23        18
          19       0.17      0.55      0.26        11
          20       0.20      0.11      0.14         9
          21       0.14      0.17      0.15         6
          22       0.00      0.00      0.00         5
          23       0.00      0.00      0.00         7
          24       0.10      0.14      0.12         7
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         3
          27       0.00      0.00      0.00        10
          28       0.00      0.00      0.00         4
          29       0.00      0.00      0.00        11
          30       0.08      0.20      0.12         5
          31       0.25      0.12      0.17         8
          32       0.00      0.00      0.00         3
          33   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


KNN model fitting considering K=4 and metric = minkowski

In [19]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4,metric='minkowski')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)


Confusion matrix, accuracy measures, classification report

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[7 5 1 ... 1 0 0]
 [2 6 0 ... 0 0 0]
 [1 3 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
              precision    recall  f1-score   support

          18       0.24      0.39      0.30        18
          19       0.20      0.55      0.29        11
          20       0.14      0.11      0.12         9
          21       0.14      0.17      0.15         6
          22       0.00      0.00      0.00         5
          23       0.00      0.00      0.00         7
          24       0.00      0.00      0.00         7
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         3
          27       0.00      0.00      0.00        10
          28       0.00      0.00      0.00         4
          29       0.00      0.00      0.00        11
          30       0.12      0.20      0.15         5
          31       0.00      0.00      0.00         8
          32       0.00      0.00      0.00         3
          33   

Naïve Bayes Classification of the same dataset

In [21]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(y_train, X_train)

X_pred = gnb.predict(y_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(X_test, X_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 7.462686567164178
