<a href="https://colab.research.google.com/github/2147118Joshua/Machine_Learning/blob/main/Support_Vector_Machine_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv("/content/car_details.csv")
df.head()
df.shape
# df.drop(columns=[&#39;Id&#39;], inplace=True)

(4340, 8)

In [4]:
#Let's drop unimportant columns
df.drop('name', inplace=True, axis=1)

In [5]:
owners=df['owner'].unique()
transmission = df['transmission'].unique()
seller_type = df['seller_type'].unique()
fuel = df['fuel'].unique()
print(owners,transmission,seller_type)

['First Owner' 'Second Owner' 'Fourth & Above Owner' 'Third Owner'
 'Test Drive Car'] ['Manual' 'Automatic'] ['Individual' 'Dealer' 'Trustmark Dealer']


In [6]:
t = {owners[0]: 0, owners[1]: 1, owners[2]: 2, owners[3]: 3, owners[4]: 4}
df['owner'] = df['owner'].map(t)

t = {transmission[0] : 0, transmission[1] : 1}
df['transmission'] = df['transmission'].map(t)

t = {seller_type[0] : 0, seller_type[1] : 1, seller_type[2] : 2}
df['seller_type'] = df['seller_type'].map(t)

t = {fuel[0] : 0, fuel[1] : 1, fuel[2] : 2, fuel[3] : 3, fuel[4] : 4}
df['fuel'] = df['fuel'].map(t)

In [10]:
features = ['transmission', 'owner']
X = df[features]
y = df['seller_type']

In [11]:
#Splitting dataset to train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=45,stratify=y)

In [12]:
#Create the SVM model

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [13]:
# SVC with linear kernel

C = 1.0 # SVM regularization parameter

# LinearSVC (linear kernel)
svc =SVC(kernel= 'linear', C=C)
# classifier = SVC(kernel='linear', random_state=0)  

svc.fit(X_train, y_train)

SVC(kernel='linear')

In [14]:
# Evaluate the trainong model (Accuracy of training model)

Trainaccuracy = cross_val_score(svc,X_train,y_train,cv=5)
svc.fit(X_train,y_train)
print("Train model accuracy:", np.mean(Trainaccuracy))

Train model accuracy: 0.7442398985519812


In [15]:
# Evaluate the Testing accuracy
y_pred1 = svc.predict(X_test)
print ('Accuracy of linear svm:', accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
# SVC with RBF kernel
# Gamma indicates the ‘spread’ of the kernel that is decision region.
#Gamma is low, the decision region is very broad.
#When gamma is high, the ‘decision boundary is high, which creates islands of decision-boundaries around data points

Accuracy of linear svm: 0.7473118279569892
[[973   0   0]
 [298   0   0]
 [ 31   0   0]]


In [16]:
rbf_svc =SVC(kernel='rbf', gamma=0.8, C=C)
rbf_svc.fit(X_train, y_train)
y_pred2 = rbf_svc.predict(X_test)
print ('Accuracy of rbf kernel:', accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Accuracy of rbf kernel: 0.7703533026113671
[[934  39   0]
 [229  69   0]
 [ 28   3   0]]


In [ ]:
# SVC with polynomial (degree 3) kernel
poly_svc =SVC(kernel='poly', degree=5, C=C)
poly_svc.fit(X, y)
y_pred3 = poly_svc.predict(X_test)
print ('Accuracy of polynomial kernel:', accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))



In [ ]:
grid = {

'C':[0.01,0.1,1,10],
'kernel' : ["linear","poly","rbf"],
'degree': [1,3,5,7],
'gamma' : [0.01,1]
}
svm =SVC()
svm_cv = GridSearchCV(svm, grid)
svm_cv.fit(X_train,y_train)

print("Best Parameters:",svm_cv.best_params_)

#print(&quot;Train Score:&quot;,svm_cv.best_score_)
print("Test Score:",svm_cv.score(X_test,y_test))